services:
  p-search:
    build: .
    container_name: p-search
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      SEARCH_DATA: ./data/search-content.json
      SEARCH_DB: /app/data/s-db.json
      SEARCH_LEARN: dataset
      SEARCH_BACKUP: "true"
    volumes:
      - ./data:/app/data