import type { ProviderInfo } from '../search/types.js';

/** Каталог провайдеров и моделей по документации OpenCode (MODELS.txt): AI-модели, инфраструктура, облака и локалки. */
export const PROVIDERS: ProviderInfo[] = [
	// --- AI-модели ----------------------------------------------------------
	{ id: 'anthropic', name: 'Anthropic', group: 'AI-модели', models: ['claude-opus-4', 'claude-sonnet-4', 'claude-haiku-4.5'] },
	{ id: 'openai', name: 'OpenAI', group: 'AI-модели', models: ['gpt-5', 'gpt-5-nano', 'gpt-4o'] },
	{ id: 'google', name: 'Google', group: 'AI-модели', models: ['gemini-2-5-pro', 'gemini-2-5-flash'] },
	{ id: 'x-ai', name: 'xAI', group: 'AI-модели', models: ['grok-4', 'grok-3'] },
	{ id: 'deepseek', name: 'DeepSeek', group: 'AI-модели', models: ['deepseek-v4-pro', 'deepseek-v3', 'deepseek-r1'] },
	{ id: 'mistral', name: 'Mistral AI', group: 'AI-модели', models: ['mistral-large', 'mistral-medium', 'mixtral-8x7b'] },
	{ id: 'moonshot', name: 'Moonshot AI', group: 'AI-модели', models: ['kimi-k2', 'moonshot-v1'] },
	{ id: 'minimax', name: 'MiniMax', group: 'AI-модели', models: ['minimax-m2.1'] },
	{ id: 'meta', name: 'Meta', group: 'AI-модели', models: ['llama-3.1-405b', 'llama-3-70b', 'codellama-70b'] },
	{ id: 'cohere', name: 'Cohere', group: 'AI-модели', models: ['command-r-plus', 'command-r'] },
	{ id: 'zhipu', name: 'Zhipu GLM', group: 'AI-модели', models: ['glm-4.6', 'glm-4-plus'] },
	{ id: 'qwen', name: 'Qwen (Алибаба)', group: 'AI-модели', models: ['qwen-2.5-72b', 'qwen-coder'] },
	{ id: 'baidu', name: 'Baidu ERNIE', group: 'AI-модели', models: ['ernie-4.0', 'ernie-bot'] },
	{ id: 'perplexity', name: 'Perplexity', group: 'AI-модели', models: ['sonar', 'sonar-pro'] },
	{ id: 'databricks', name: 'Databricks', group: 'AI-модели', models: ['dbrx', 'llama-3'] },
	{ id: 'ai21', name: 'AI21 Labs', group: 'AI-модели', models: ['jamba-1.5', 'jurassic-2'] },
	{ id: 'writer', name: 'Writer', group: 'AI-модели', models: ['palmyra-x'] },
	{ id: 'gigachat', name: 'GigaChat', group: 'AI-модели', models: ['gigachat-max'] },
	{ id: 'sber', name: 'Сбер', group: 'AI-модели', models: ['gigachat-pro'] },
	{ id: 'abacus', name: 'Abacus AI', group: 'AI-модели', models: ['gpt-4', 'claude-3'] },
	{ id: 'apple', name: 'Apple', group: 'AI-модели', models: ['openelm-3b'] },
	// --- Инфраструктура -----------------------------------------------------
	{ id: 'groq', name: 'Groq', group: 'Инфраструктура', models: ['llama-3.1', 'mixtral-8x7b'] },
	{ id: 'cerebras', name: 'Cerebras', group: 'Инфраструктура', models: ['qwen-3-coder-480b'] },
	{ id: 'fireworks', name: 'Fireworks AI', group: 'Инфраструктура', models: ['kimi-k2-instruct'] },
	{ id: 'together', name: 'Together AI', group: 'Инфраструктура', models: ['llama-3.1-405b', 'qwen-2.5-72b'] },
	{ id: 'baseten', name: 'Baseten', group: 'Инфраструктура', models: ['kimi-k2-instruct'] },
	{ id: 'nvidia', name: 'NVIDIA NIM', group: 'Инфраструктура', models: ['nemotron-3-super-120b', 'nemotron-mixture'] },
	{ id: 'huggingface', name: 'Hugging Face', group: 'Инфраструктура', models: ['kimi-k2-instruct', 'glm-4.6'] },
	{ id: 'deepinfra', name: 'Deep Infra', group: 'Инфраструктура', models: ['llama', 'qwen'] },
	{ id: 'nebius', name: 'Nebius Token Factory', group: 'Инфраструктура', models: ['kimi-k2-instruct'] },
	{ id: 'gmi', name: 'GMI Cloud', group: 'Инфраструктура', models: ['llama', 'qwen'] },
	{ id: 'iotnet', name: 'IO.NET', group: 'Инфраструктура', models: ['llama', 'qwen', 'deepseek'] },
	{ id: 'cortecs', name: 'Cortecs', group: 'Инфраструктура', models: ['kimi-k2-instruct'] },
	{ id: 'frogbot', name: 'FrogBot', group: 'Инфраструктура', models: ['llama'] },
	{ id: 'venice', name: 'Venice AI', group: 'Инфраструктура', models: ['llama', 'qwen'] },
	{ id: 'poolside', name: 'Poolside', group: 'Инфраструктура', models: ['poolside'] },
	{ id: 'za', name: 'Z.AI', group: 'Инфраструктура', models: ['z-ai'] },
	{ id: 'modal', name: 'Modal', group: 'Инфраструктура', models: ['endpoints'] },
	{ id: '302ai', name: '302.AI', group: 'Инфраструктура', models: ['gpt', 'claude', 'gemini'] },
	// --- Облака и шлюзы -----------------------------------------------------
	{ id: 'amazon', name: 'Amazon Bedrock', group: 'Облака и шлюзы', models: ['claude', 'llama', 'mistral'] },
	{ id: 'azure', name: 'Azure OpenAI', group: 'Облака и шлюзы', models: ['gpt-4o', 'gpt-35'] },
	{ id: 'azure-cognitive', name: 'Azure Cognitive Services', group: 'Облака и шлюзы', models: ['openai', 'phi'] },
	{ id: 'google-vertex', name: 'Google Vertex AI', group: 'Облака и шлюзы', models: ['gemini'] },
	{ id: 'digitalocean', name: 'DigitalOcean', group: 'Облака и шлюзы', models: ['llama', 'qwen', 'deepseek'] },
	{ id: 'openrouter', name: 'OpenRouter', group: 'Облака и шлюзы', models: ['300+ моделей'] },
	{ id: 'github-copilot', name: 'GitHub Copilot', group: 'Облака и шлюзы', models: ['gpt', 'claude'] },
	{ id: 'gitlab-duo', name: 'GitLab Duo', group: 'Облака и шлюзы', models: ['claude-haiku-4.5', 'claude-sonnet-4.5', 'claude-opus-4.5'] },
	{ id: 'ollama-cloud', name: 'Ollama Cloud', group: 'Облака и шлюзы', models: ['gpt-oss-20b-cloud'] },
	{ id: 'vercel', name: 'Vercel AI Gateway', group: 'Облака и шлюзы', models: ['gpt', 'claude'] },
	{ id: 'cloudflare', name: 'Cloudflare AI Gateway', group: 'Облака и шлюзы', models: ['gpt-4o', 'claude'] },
	{ id: 'cloudflare-ai', name: 'Cloudflare Workers AI', group: 'Облака и шлюзы', models: ['workers-ai'] },
	{ id: 'helicone', name: 'Helicone', group: 'Облака и шлюзы', models: ['routing'] },
	{ id: 'llm-gateway', name: 'LLM Gateway', group: 'Облака и шлюзы', models: ['gpt', 'claude'] },
	{ id: 'zenmux', name: 'ZenMux', group: 'Облака и шлюзы', models: ['routing'] },
	{ id: 'stackit', name: 'STACKIT', group: 'Облака и шлюзы', models: ['llama'] },
	{ id: 'ovhcloud', name: 'OVHcloud AI Endpoints', group: 'Облака и шлюзы', models: ['llama', 'mistral'] },
	{ id: 'sap', name: 'SAP AI Core', group: 'Облака и шлюзы', models: ['sap-ai'] },
	{ id: 'snowflake', name: 'Snowflake Cortex', group: 'Облака и шлюзы', models: ['cortex'] },
	{ id: 'scaleway', name: 'Scaleway', group: 'Облака и шлюзы', models: ['llama', 'qwen'] },
	{ id: 'opencode-zen', name: 'OpenCode Zen', group: 'Облака и шлюзы', models: ['zen'] },
	// --- Локальные ----------------------------------------------------------
	{ id: 'ollama', name: 'Ollama', group: 'Локальные', models: ['llama-3', 'mistral', 'qwen-2', 'gpt-oss'] },
	{ id: 'lmstudio', name: 'LM Studio', group: 'Локальные', models: ['gemma-3n-4b', 'локальные-gguf'] },
	{ id: 'llamacpp', name: 'llama.cpp', group: 'Локальные', models: ['qwen3-coder-a3b', 'gguf'] },
	{ id: 'atomic-chat', name: 'Atomic Chat', group: 'Локальные', models: ['openapi-совместимая'] },
	{ id: 'vllm', name: 'vLLM', group: 'Локальные', models: ['openai-совместимая'] },
	{ id: 'localai', name: 'LocalAI', group: 'Локальные', models: ['llama', 'gpt4all'] },
	{ id: 'textgen', name: 'oobabooga', group: 'Локальные', models: ['llama', 'mistral'] },
	{ id: 'petals', name: 'Petals', group: 'Локальные', models: ['bloom-176b'] }
];