import type { ProviderInfo } from '../search/types.js';

/** Каталог из 75+ внешних провайдеров данных и AI-моделей. */
export const PROVIDERS: ProviderInfo[] = [
	{ id: 'anthropic', name: 'Anthropic', group: 'AI-модели', models: ['claude-3-5-sonnet', 'claude-3-opus', 'claude-3-haiku'] },
	{ id: 'openai', name: 'OpenAI', group: 'AI-модели', models: ['gpt-4o', 'gpt-4-turbo', 'gpt-3-5-turbo'] },
	{ id: 'google', name: 'Google', group: 'AI-модели', models: ['gemini-1-5-pro', 'gemini-1-5-flash', 'gemini-1-0'] },
	{ id: 'mistral', name: 'Mistral AI', group: 'AI-модели', models: ['mistral-large', 'mistral-medium', 'mixtral-8x7b'] },
	{ id: 'meta', name: 'Meta', group: 'AI-модели', models: ['llama-3-1-405b', 'llama-3-70b', 'codellama-70b'] },
	{ id: 'cohere', name: 'Cohere', group: 'AI-модели', models: ['command-r-plus', 'command-r', 'command'] },
	{ id: 'amazon', name: 'Amazon Bedrock', group: 'Облака', models: ['claude-3-sonnet', 'llama-3-1', 'mistral-large'] },
	{ id: 'azure', name: 'Microsoft Azure', group: 'Облака', models: ['azure-gpt-4o', 'azure-gpt-35', 'phi-3'] },
	{ id: 'yandex', name: 'Яндекс', group: 'AI-модели', models: ['yandexgpt', 'yandexgpt-pro', 'yandexart'] },
	{ id: 'sber', name: 'Сбер', group: 'AI-модели', models: ['gigachat', 'gigachat-pro', 'gigachat-lite'] },
	{ id: 'vk', name: 'VK', group: 'AI-модели', models: ['vk-gpt', 'kandinsky-3', 'kandinsky-4'] },
	{ id: 'gigachat', name: 'GigaChat', group: 'AI-модели', models: ['gigachat-max', 'gigachat-plus'] },
	{ id: 'deepseek', name: 'DeepSeek', group: 'AI-модели', models: ['deepseek-chat', 'deepseek-coder'] },
	{ id: 'qwen', name: 'Qwen (Алибаба)', group: 'AI-модели', models: ['qwen-2-5-72b', 'qwen-2-5-coder'] },
	{ id: 'baidu', name: 'Baidu ERNIE', group: 'AI-модели', models: ['ernie-4-0', 'ernie-bot'] },
	{ id: 'zhipu', name: 'Zhipu GLM', group: 'AI-модели', models: ['glm-4', 'glm-4-plus'] },
	{ id: 'moonshot', name: 'Moonshot Kimi', group: 'AI-модели', models: ['kimi-k2', 'moonshot-v1'] },
	{ id: 'x-ai', name: 'xAI', group: 'AI-модели', models: ['grok-2', 'grok-2-mini'] },
	{ id: 'perplexity', name: 'Perplexity', group: 'AI-модели', models: ['sonar', 'sonar-pro'] },
	{ id: 'groq', name: 'Groq', group: 'Инфраструктура', models: ['llama-3-1-8b', 'mixtral-8x7b'] },
	{ id: 'together', name: 'Together AI', group: 'Инфраструктура', models: ['llama-3-1-405b', 'qwen-2-5-72b'] },
	{ id: 'fireworks', name: 'Fireworks AI', group: 'Инфраструктура', models: ['llama-3-1', 'qwen-2-5'] },
	{ id: 'replicate', name: 'Replicate', group: 'Инфраструктура', models: ['llama-3', 'flux-schnell'] },
	{ id: 'nvidia', name: 'NVIDIA NIM', group: 'Инфраструктура', models: ['llama-3-1-70b', 'mistral-7b'] },
	{ id: 'huggingface', name: 'Hugging Face', group: 'Инфраструктура', models: ['zephyr', 'falcon'] },
	{ id: 'ollama', name: 'Ollama', group: 'Локальные', models: ['llama3', 'mistral', 'qwen2'] },
	{ id: 'lamacpp', name: 'llama.cpp', group: 'Локальные', models: ['ggml', 'gguf'] },
	{ id: 'vllm', name: 'vLLM', group: 'Локальные', models: ['openai-совместимая'] },
	{ id: 'localai', name: 'LocalAI', group: 'Локальные', models: ['llama', 'gpt4all'] },
	{ id: 'textgen', name: 'oobabooga', group: 'Локальные', models: ['llama', 'mistral'] },
	{ id: 'apple', name: 'Apple Intelligence', group: 'AI-модели', models: ['openelm-3b', 'ferret'] },
	{ id: 'ibm', name: 'IBM watsonx', group: 'Облака', models: ['granite', 'llama-3'] },
	{ id: 'oracle', name: 'Oracle OCI', group: 'Облака', models: ['llama-3', 'cohere'] },
	{ id: 'petals', name: 'Petals', group: 'Локальные', models: ['bloom-176b'] },
	{ id: 'databricks', name: 'Databricks', group: 'AI-модели', models: ['dbrx', 'llama-3'] },
	{ id: 'snowflake', name: 'Snowflake Arctic', group: 'Облака', models: ['arctic-instruct'] },
	{ id: 'ai21', name: 'AI21 Labs', group: 'AI-модели', models: ['jamba-1-5', 'jurassic-2'] },
	{ id: 'writer', name: 'Writer', group: 'AI-модели', models: ['palmyra-x'] },
	{ id: 'abacus', name: 'Abacus AI', group: 'AI-модели', models: ['gpt-4', 'claude-3'] },
	{ id: 'anyscale', name: 'Anyscale', group: 'Инфраструктура', models: ['llama-3-1', 'mixtral'] },
	{ id: 'baseten', name: 'Baseten', group: 'Инфраструктура', models: ['llama-3', 'mixtral'] },
	{ id: 'cerebras', name: 'Cerebras', group: 'Инфраструктура', models: ['llama-3-1-70b'] },
	{ id: 'chroma', name: 'ChromaDB', group: 'Базы данных', models: ['embedder'] },
	{ id: 'pinecone', name: 'Pinecone', group: 'Базы данных', models: ['vector-embedder'] },
	{ id: 'weaviate', name: 'Weaviate', group: 'Базы данных', models: ['vector-index'] },
	{ id: 'qdrant', name: 'Qdrant', group: 'Базы данных', models: ['vector-index'] },
	{ id: 'milvus', name: 'Milvus', group: 'Базы данных', models: ['vector-index'] },
	{ id: 'vespa', name: 'Vespa', group: 'Базы данных', models: ['search-index'] },
	{ id: 'elasticsearch', name: 'Elasticsearch', group: 'Базы данных', models: ['bm25', 'vector'] },
	{ id: 'opensearch', name: 'OpenSearch', group: 'Базы данных', models: ['bm25'] },
	{ id: 'meilisearch', name: 'Meilisearch', group: 'Базы данных', models: ['typo-tolerance'] },
	{ id: 'typesense', name: 'Typesense', group: 'Базы данных', models: ['geosearch'] },
	{ id: 'algolia', name: 'Algolia', group: 'Базы данных', models: ['algolia-search'] },
	{ id: 'redis', name: 'Redis', group: 'Базы данных', models: ['redisearch'] },
	{ id: 'sqlite', name: 'SQLite FTS5', group: 'Базы данных', models: ['fts5'] },
	{ id: 'postgres', name: 'PostgreSQL', group: 'Базы данных', models: ['tsvector'] },
	{ id: 'mysql', name: 'MySQL', group: 'Базы данных', models: ['fulltext'] },
	{ id: 'mongo', name: 'MongoDB Atlas', group: 'Базы данных', models: ['atlas-search'] },
	{ id: 'clickhouse', name: 'ClickHouse', group: 'Базы данных', models: ['fulltext'] },
	{ id: 'duckdb', name: 'DuckDB', group: 'Базы данных', models: ['fts'] },
	{ id: 'turbopuffer', name: 'Turbopuffer', group: 'Базы данных', models: ['vector'] },
	{ id: 'neon', name: 'Neon', group: 'Базы данных', models: ['pgvector'] },
	{ id: 'supabase', name: 'Supabase', group: 'Базы данных', models: ['pgvector'] },
	{ id: 'firebase', name: 'Firebase', group: 'Базы данных', models: ['firestore'] },
	{ id: 'algolia-ecommerce', name: 'Algolia Commerce', group: 'Базы данных', models: ['ecommerce-search'] },
	{ id: 'bigquery', name: 'Google BigQuery', group: 'Облака', models: ['sql-search'] },
	{ id: 'datastax', name: 'DataStax Astra', group: 'Облака', models: ['vector'] },
	{ id: 'cassandra', name: 'Cassandra', group: 'Базы данных', models: ['cql'] },
	{ id: 'dynamodb', name: 'Amazon DynamoDB', group: 'Облака', models: ['nosql'] },
	{ id: 'vercel', name: 'Vercel', group: 'Облака', models: ['edge-functions'] },
	{ id: 'cloudflare', name: 'Cloudflare Workers', group: 'Облака', models: ['worker-ai'] },
	{ id: 'deno', name: 'Deno Deploy', group: 'Облака', models: ['edge-runtime'] },
	{ id: 'fly', name: 'Fly.io', group: 'Облака', models: ['machines'] },
	{ id: 'railway', name: 'Railway', group: 'Облака', models: ['railway-app'] },
	{ id: 'render', name: 'Render', group: 'Облака', models: ['web-service'] },
	{ id: 'digitalocean', name: 'DigitalOcean', group: 'Облака', models: ['droplet'] },
	{ id: 'heroku', name: 'Heroku', group: 'Облака', models: ['dyno'] },
	{ id: 'scaleway', name: 'Scaleway', group: 'Облака', models: ['instance'] },
	{ id: 'telegram', name: 'Telegram Bot API', group: 'Мессенджеры', models: ['bot-api'] },
	{ id: 'discord', name: 'Discord Bot', group: 'Мессенджеры', models: ['slash-commands'] },
	{ id: 'slack', name: 'Slack Apps', group: 'Мессенджеры', models: ['slash-commands'] },
	{ id: 'whatsapp', name: 'WhatsApp Business', group: 'Мессенджеры', models: ['cloud-api'] },
	{ id: 'viber', name: 'Viber', group: 'Мессенджеры', models: ['bot-api'] },
	{ id: 'vk-bot', name: 'VK Bot', group: 'Мессенджеры', models: ['callback-api'] },
	{ id: 'zenmoney', name: 'ZenMoney', group: 'Финансы', models: ['open-api'] },
	{ id: 'tinkoff', name: 'Тинькофф', group: 'Финансы', models: ['open-api'] },
	{ id: 'sberbank', name: 'Сбер Банк', group: 'Финансы', models: ['open-api'] },
	{ id: 'yoomoney', name: 'ЮMoney', group: 'Финансы', models: ['payments'] },
	{ id: 'qiwi', name: 'QIWI', group: 'Финансы', models: ['payments'] }
];